version: "3.9"

services:
  backend:
    build: ./backend
    container_name: apartment-backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/apartmentdb
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: apartment-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo:5
    container_name: apartment-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
